apiVersion: v1
kind: LimitRange
metadata:
   name: testlimit
   namespace: cricbuzz

spec:
   limits:
      - default:
           cpu: 200m
           memory: 500Mi
        defaultRequest:
           cpu: 100m
           memory: 250Mi
        min:
           cpu: 90m
           memory: 150Mi
        max:
           cpu: 500m
           memory: 700Mi
        maxLimitRequestRatio:
           memory: 2
           cpu: 2
        type: Container
