apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    app: myapp
    type: frontend
spec:
  containers:
    - name: kumar
      image: abhay10371/nginx-custom:v2
      resources:
         requests:
            memory: 200Mi
            cpu: 100m
         limits:
            memory: 400Mi
            cpu: 200m      

