apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
  labels: 
    name: first-deployment     
spec:
  replicas: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: myapp  
  template:
    metadata:
      name: pod
      labels:
        app: myapp
    spec:
      containers:
        - name: abhay
          image: abhay10371/nginx-custom
