apiVersion: v1
kind: Pod
metadata:
  name: pod7
  labels:
    app: myapp1
    type: frontend
spec:
  containers:
    - name: kumar
      image: abhay10371/nginx-custom
      imagePullPolicy: Never
  affinity:
       nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
               - preference:
                      matchExpressions:
                          - key: size
                            operator: In
                            values: 
                               - extralarge
                 weight: 1 
                                                 


