apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: myapp1
    type: frontend
spec:
  containers:
    - name: kumar
      image: abhay10371/nginx-custom
      imagePullPolicy: Never
  affinity:
    nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                        - matchExpressions:
                                - key: size
                                  operator: In
                                  values: 
                                        - extralarge
