apiVersion: v1
kind: ReplicationController
metadata:
  name: first-rc
  labels: 
    appname: cricbuzz     
spec:
  replicas: 2
  selector:
    app: myapp1
  template:
    metadata:
      name: firstpod
      labels:
        app: myapp1
    spec:
      containers:
        - name: abhay
          image: abhay10371/nginx-custom
