apiVersion: v1
kind: ReplicationController
metadata:
  name: firstreplicationcontroller
  labels: 
    appname: cricbuzz
spec:
  replicas: 3
  template:
    metadata:
      name: firstpod1
      labels:
        type: app
    spec:
      containers:
        - name: abhay
          image: abhay10371/nginx-custom
