apiVersion: v1
kind: Pod
metadata:
  name: pod4
  labels:
    app: myapp1
    type: frontend
spec:
  containers:
    - name: kumar
      image: abhay10371/nginx-custom
      imagePullPolicy: Never
  tolerations:
    - effect: "NoExecute"
      key: "mysize"
      operator: "Equal"
      value: "large"
      tolerationSeconds: 60        
