## Inject ConfigMap variable in pod ##
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: myapp1
    type: frontend
spec:
  containers:
    - name: kumar
      image: abhay10371/nginx-custom:v2
      env:
        - name: variablefromcm
          valueFrom:
             configMapKeyRef:
                key: variable3
                name: envcm
