## Inject ConfigMap from files in pod ##
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: myapp1
    type: frontend
spec:
  containers:
    - name: kumar
      image: abhay10371/nginx-custom
      env:
        - name: variablefromcm2
          valueFrom:
             configMapKeyRef:
                key: env.sh
                name: fromfilecm
