## Inject ConfigMap (Variables) as Files in Pod ##
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: myapp1
    type: frontend
spec:
  containers:
    - name: kumar
      image: abhay10371/nginx-custom
      volumeMounts:
          - name: test  
            mountPath: "/config"
            readOnly: true
  volumes:
    - name: test
      configMap: 
          name: envcm
