## Inject ConfigMap variable in pod ##
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: myapp1
    type: frontend
spec:
  containers:
    - name: kumar
      image: abhay10371/nginx-custom
      volumeMounts:
          - mountPath: /secrets
            name: testsec
  volumes:
    - name: testsec
      secret:
          secretName: fromenvfile
